language: node_js
node_js:
- 11.1.0
before_install:
script:
- yarn test
after_success:
### Prepare for GitHub
- openssl aes-256-cbc -K $encrypted_b77908ae0d8e_key -iv $encrypted_b77908ae0d8e_iv -in ./id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- git config --global user.email "h.taku86@gmail.com"
- git config --global user.name "takuyahara"
- git config --global url."git@github.com:".insteadOf "https://github.com/"
- git config remote.storybook.url https://github.com/takuyahara/deploy-app-storybook-docs.git
- git config remote.storybook.fetch "+refs/heads/storybook:refs/remotes/origin/storybook"
### Build Storybook
- git checkout -b storybook master
- mv netlify.storybook.toml netlify.toml
- git add .
- git commit -m "$TRAVIS_COMMIT_MESSAGE"
- git push -u origin storybook --force
# Generate docs by TypeDoc
- git checkout -b gh-pages master
- git subtree add --prefix docs origin gh-pages
- rm -rf docs
- node node_modules/.bin/typedoc --out docs src
- touch docs/.nojekyll
- git add docs --force
- git commit -m "$TRAVIS_COMMIT_MESSAGE"
- git subtree push --prefix docs origin gh-pages

branches:
  only:
  - master